// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package parser

type QuerySlice []Query
type IndexSlice []Index

func (t QuerySlice) Where(predicate func(source Query) bool) (result QuerySlice) {
	for _, value := range t {
		if predicate(value) {
			result = append(result, value)
		}
	}
	return
}

func (t QuerySlice) Select(selector func(source Query) Index) (result IndexSlice) {
	for _, value := range t {
		result = append(result, selector(value))
	}
	return
}
